# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-03-26 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_calls', models.IntegerField(blank=True, default=0, null=True)),
                ('entered_val', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
