# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-03-26 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_calls', models.IntegerField(blank=True, default=0, null=True)),
                ('entered_val', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StupidCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_calls', models.IntegerField(blank=True, default=0, null=True)),
                ('entered_val', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='StoreCalls',
            new_name='DumbCalls',
        ),
    ]
