# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-03-26 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0002_auto_20210326_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dumbcalls',
            name='no_of_calls',
        ),
        migrations.RemoveField(
            model_name='fatcalls',
            name='no_of_calls',
        ),
        migrations.RemoveField(
            model_name='stupidcalls',
            name='no_of_calls',
        ),
    ]
