# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-03-26 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0003_auto_20210326_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dumb_val', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot_tutorial.DumbCalls')),
                ('fat_val', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot_tutorial.FatCalls')),
                ('stupid_val', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot_tutorial.StupidCalls')),
            ],
        ),
    ]
