# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-03-26 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0005_auto_20210326_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatclick',
            name='fat_val',
        ),
    ]
