# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-03-26 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0006_remove_fatclick_fat_val'),
    ]

    operations = [
        migrations.CreateModel(
            name='DumbClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_call', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StupidClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_call', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
