# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-03-26 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0007_dumbclick_stupidclick'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FatCalls',
            new_name='AllCalls',
        ),
        migrations.DeleteModel(
            name='DumbCalls',
        ),
        migrations.DeleteModel(
            name='StupidCalls',
        ),
    ]
