# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-03-26 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0008_auto_20210326_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dumbclick',
            name='no_of_call',
        ),
        migrations.RemoveField(
            model_name='fatclick',
            name='no_of_call',
        ),
        migrations.RemoveField(
            model_name='stupidclick',
            name='no_of_call',
        ),
        migrations.AddField(
            model_name='dumbclick',
            name='dumb_click',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fatclick',
            name='fat_click',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stupidclick',
            name='stupid_click',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
