# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-03-26 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0009_auto_20210326_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumbclick',
            name='dumb_click',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stupidclick',
            name='stupid_click',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
