# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-28 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0012_allcalls_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcalls',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allcalls',
            name='created_by',
            field=models.CharField(default=b'', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='allcalls',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='allcalls',
            name='updated_by',
            field=models.CharField(default=b'', editable=False, max_length=100),
        ),
    ]
