# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-02 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0013_auto_20210328_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcalls',
            name='user',
        ),
    ]
