# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-03 05:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0016_auto_20210403_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='getuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='getuser',
            name='created_by',
            field=models.CharField(default=b'', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='getuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='getuser',
            name='updated_by',
            field=models.CharField(default=b'', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='getuser',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
