# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-03 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0018_getuser_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DumbClick',
        ),
        migrations.DeleteModel(
            name='StupidClick',
        ),
    ]
